### ISSUE TITLE
readme的rtorrent + irssi-autodl步骤中，一键脚本404

### ISSUE THREAD

**Issue by yoonching** [Rhilip/Byrbt-Autoseed#7]
如题~

**Comment by Rhilip** [comment]
Maybe you should check the repo [arakasi72/rtinst](https://github.com/arakasi72/rtinst) to see the Installation Guide.
It has been changed, but I didn't update my `README.md` immediately for no necessary.

------------

fix in https://github.com/Rhilip/Pt-Autoseed/commit/1657683759bc1bad436960eddf97956ff103b0c6
Thanks anyway~
