### ISSUE TITLE
byrbt bgmtv_url field enabled today, would you like to support it?

### ISSUE THREAD

**Issue by FredericDT** [Rhilip/Byrbt-Autoseed#8]
input field name: `bgmtv_url`

supporting bgmtv subject id

you can provided this field like `899`, which refers to https://bgm.tv/subject/899

**Comment by Rhilip** [comment]
I will support it ASAP.

**Comment by FredericDT** [comment]
https://github.com/Rhilip/Pt-Autoseed/commit/946d997108d3dc92dbc5260c8a4bf905007d2c98#r30728474

**Comment by Rhilip** [comment]
@FredericDT It seems unnecessary to provide Bangumi subject field in other category.
But I will remove this category judgment. 
If you have another request about bgmurl field in byrbt autoseed, please reopen this issue.
